version: 0.0
os: linux
files:
  - source: .
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/before
      timeout: 300
      runas: root
  Install:
    - location: scripts/install
      timeout: 300
      runas: root